# Generated by Django 6.0.5 on 2026-05-24 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0019_backfill_original_filename'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='案件组名称')),
                ('note', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '案件组',
                'verbose_name_plural': '案件组',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='case',
            name='group_sequence',
            field=models.PositiveIntegerField(default=0, verbose_name='组内顺序'),
        ),
        migrations.AddField(
            model_name='historicalcase',
            name='group_sequence',
            field=models.PositiveIntegerField(default=0, verbose_name='组内顺序'),
        ),
        migrations.AddField(
            model_name='case',
            name='case_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='cases.casegroup', verbose_name='案件组'),
        ),
        migrations.AddField(
            model_name='historicalcase',
            name='case_group',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cases.casegroup', verbose_name='案件组'),
        ),
    ]
