# Generated by Django 6.0.5 on 2026-06-04 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0023_add_cloud_storage_to_folder_bindings'),
        ('contracts', '0030_add_cloud_storage_to_folder_bindings'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['status'], name='cases_case_status_5f99d2_idx'),
        ),
    ]
