# Generated by Django 6.0.5 on 2026-06-04 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0024_case_cases_case_status_5f99d2_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="casefolderbinding",
            name="storage_type",
            field=models.CharField(
                choices=[
                    ("local", "本地文件系统"),
                    ("webdav", "WebDAV"),
                    ("onedrive", "OneDrive"),
                    ("s3", "S3 兼容存储"),
                    ("google_drive", "Google Drive"),
                    ("dropbox", "Dropbox"),
                ],
                default="local",
                max_length=20,
                verbose_name="存储类型",
            ),
        ),
    ]
