# Generated by Django 6.0.6 on 2026-06-14 12:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0025_alter_casefolderbinding_storage_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='caselog',
            index=models.Index(fields=['-created_at'], name='cases_caselog_created_idx'),
        ),
    ]
