# Generated by Django 6.0.6 on 2026-06-14 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0026_add_performance_indexes_round2'),
        ('contracts', '0033_add_storage_to_folder_root_preset'),
        ('reminders', '0005_reminder_include_in_important_time'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='reminder',
            index=models.Index(fields=['reminder_type', 'due_at'], name='reminders_type_due_idx'),
        ),
    ]
