# Generated by Django 6.0.6 on 2026-06-16 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reminders", "0006_add_performance_indexes_round2"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="reminder",
            name="reminders_type_due_idx",
        ),
    ]
