# Generated by Django 6.0.6 on 2026-06-11 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DocumentParsingTool",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ],
            options={
                "verbose_name": "文档解析",
                "verbose_name_plural": "文档解析",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DocumentParsingTask",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("file_name", models.CharField(max_length=255, verbose_name="文件名")),
                ("file_path", models.CharField(max_length=500, verbose_name="文件路径")),
                ("file_size", models.PositiveIntegerField(default=0, verbose_name="文件大小（字节）")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("processing", "处理中"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("backend_used", models.CharField(blank=True, max_length=50, verbose_name="解析后端")),
                ("text", models.TextField(blank=True, verbose_name="纯文本")),
                ("markdown", models.TextField(blank=True, verbose_name="Markdown")),
                ("metadata", models.JSONField(blank=True, default=dict, verbose_name="元数据")),
                ("error_message", models.TextField(blank=True, verbose_name="错误信息")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("completed_at", models.DateTimeField(blank=True, null=True, verbose_name="完成时间")),
            ],
            options={
                "verbose_name": "解析任务",
                "verbose_name_plural": "解析任务",
                "ordering": ["-created_at"],
            },
        ),
    ]
