"""MCP tools 顶层导出"""

from mcp_server.tools.automation import (
    ai_ollama,
    assign_sms_case,
    auto_namer_process,
    auto_namer_process_by_path,
    cleanup_resources,
    clear_cache,
    delete_court_sms,
    download_sms_document,
    download_sms_documents,
    get_captcha_image,
    get_cache_statistics,
    get_court_sms_detail,
    get_automation_config,
    get_automation_status,
    get_performance_metrics,
    get_resource_usage,
    get_statistics_report,
    health_check,
    list_court_sms,
    optimize_concurrency,
    process_document,
    process_document_by_path,
    reset_performance_metrics,
    retry_sms_processing,
    submit_captcha_answer,
    submit_court_sms,
    warm_up_cache,
)

# 条件导入：网上立案
try:
    from mcp_server.tools.automation import (
        execute_court_filing,
        get_court_filing_case_info,
        get_court_filing_session,
    )
    _HAS_FILING = True
except ImportError:
    _HAS_FILING = False

# 条件导入：诉讼保全
try:
    from mcp_server.tools.automation import (
        bind_guarantee_quote,
        delete_guarantee_binding,
        delete_guarantee_quote,
        ensure_guarantee_quote,
        execute_guarantee,
        get_guarantee_case_info,
        get_guarantee_session,
        retry_guarantee_quote,
    )
    _HAS_GUARANTEE = True
except ImportError:
    _HAS_GUARANTEE = False

# 条件导入：财产保全询价
try:
    from mcp_server.tools.automation import (
        create_preservation_quote,
        execute_preservation_quote,
        get_preservation_quote,
        list_preservation_quotes,
        retry_preservation_quote,
    )
    _HAS_QUOTE = True
except ImportError:
    _HAS_QUOTE = False
from mcp_server.tools.cases import (
    add_case_party,
    assign_lawyer,
    browse_case_folders,
    calculate_litigation_fee,
    create_case,
    create_case_folder_binding,
    create_case_log,
    create_case_number,
    create_full_case,
    create_grant,
    create_scan_stage,
    create_template_binding,
    delete_all_materials,
    delete_case,
    delete_case_assignment,
    delete_case_folder_binding,
    delete_case_log,
    delete_case_number,
    delete_case_party,
    delete_grant,
    delete_material,
    delete_template_binding,
    generate_case_template,
    get_case,
    get_case_assignment,
    get_case_folder_binding,
    get_case_log,
    get_case_number,
    get_case_party,
    get_cause,
    get_contract_folder_path,
    get_scan_status,
    list_available_templates,
    list_bind_candidates,
    list_case_assignments,
    list_case_cloud_storage_accounts,
    list_case_logs,
    list_case_numbers,
    list_case_parties,
    list_cases,
    list_causes_data,
    list_causes_tree,
    list_courts_data,
    get_grant,
    list_grants,
    list_scan_subfolders,
    list_template_bindings,
    rename_material_group,
    save_group_order,
    search_cases,
    start_folder_scan,
    unified_generate,
    update_case,
    update_case_assignment,
    update_case_log,
    update_case_number,
    update_case_party,
    update_grant,
    bind_materials,
)
from mcp_server.tools.chat_records import (
    cancel_extract_recording,
    create_export,
    create_project,
    delete_recording,
    delete_screenshot,
    download_export,
    extract_recording,
    get_export_statuses,
    get_export_task,
    get_export_types,
    get_recording,
    list_projects,
    list_recordings,
    list_screenshots,
    reorder_screenshots,
    reset_extract_recording,
    update_recording,
    update_screenshot,
)
from mcp_server.tools.clients import (
    check_oa_credential,
    create_client,
    create_property_clue,
    delete_client,
    delete_identity_doc,
    delete_property_clue,
    enterprise_prefill,
    enterprise_search,
    get_client,
    get_identity_doc,
    get_identity_doc_task,
    get_property_clue,
    get_property_clue_content_template,
    list_clients,
    list_clients_with_docs,
    list_property_clues,
    merge_id_card_manual,
    parse_client_text,
    submit_identity_doc_recognition,
    update_client,
    update_property_clue,
    validate_id_card,
)
from mcp_server.tools.contacts import (
    create_contact,
    delete_contact,
    get_contact,
    list_contacts,
    search_contacts,
    update_contact,
)
from mcp_server.tools.contract_review import (
    confirm_party,
    download_normalized_result,
    download_review_original,
    download_review_result,
    get_review_models,
    get_review_status,
    normalize_contract_format,
    upload_contract_for_review,
)
from mcp_server.tools.contracts import (
    browse_folders,
    clear_all_archive_materials,
    confirm_archive,
    confirm_contract_scan,
    create_contract,
    create_contract_with_cases,
    create_folder_binding,
    create_payment,
    create_supplementary_agreement,
    delete_archive_material,
    delete_contract,
    delete_folder_binding,
    delete_payment,
    delete_supplementary_agreement,
    download_archive_item,
    generate_archive_folder,
    get_archive_checklist,
    get_contract,
    get_contract_all_parties,
    get_contract_scan_status,
    get_folder_binding,
    get_latest_contract_scan,
    get_supplementary_agreement,
    learn_archive_rules,
    list_cloud_storage_accounts,
    list_contracts,
    list_contract_scan_subfolders,
    list_supplementary_agreements,
    move_archive_material,
    reorder_archive_materials,
    reset_and_resync_case_materials,
    scale_to_a4,
    start_contract_scan,
    sync_case_materials,
    toggle_compact_archive,
    update_contract,
    update_contract_lawyers,
    update_payment,
    update_supplementary_agreement,
)
from mcp_server.tools.doc_convert import convert_document, list_doc_convert_types
from mcp_server.tools.doc_converter import (
    cancel_conversion_job,
    delete_conversion_job,
    doc_converter_health_check,
    download_converted_files,
    get_conversion_progress,
    save_to_directory,
)
from mcp_server.tools.documents import (
    analyze_template,
    confirm_mappings,
    create_document_template,
    create_folder_template,
    create_mapping,
    create_placeholder,
    delete_archive_overrides,
    delete_document_template,
    delete_folder_template,
    delete_mapping,
    delete_placeholder,
    download_authorization_package,
    download_authority_letter,
    download_contract_document,
    download_contract_folder,
    download_delay_delivery_application,
    download_full_preservation_package,
    download_legal_rep_certificate,
    download_litigation_document,
    download_power_of_attorney,
    download_power_of_attorney_combined,
    download_preservation_application,
    download_supplementary_agreement,
    extract_template_placeholders,
    generate_complaint,
    generate_defense,
    get_archive_overrides,
    get_custom_fields,
    get_document_template,
    get_fill_history,
    get_folder_template,
    get_preview_html,
    get_statistics,
    get_undefined_placeholders,
    get_placeholder,
    get_placeholder_by_key,
    list_document_templates,
    list_folder_templates,
    list_mappings,
    list_placeholders,
    list_template_library_files,
    match_templates,
    preview_archive_context,
    preview_contract_context,
    preview_fill,
    preview_litigation_context,
    preview_placeholders,
    preview_supplementary_agreement_context,
    reorder_evidence_items,
    save_archive_overrides,
    update_document_template,
    update_folder_template,
    update_mapping,
    update_placeholder,
    validate_folder_structure,
)
from mcp_server.tools.enterprise_data import (
    get_company_personnel,
    get_company_profile,
    get_company_risks,
    get_company_shareholders,
    get_person_profile,
    list_enterprise_providers,
    search_bidding_info,
    search_companies,
)
from mcp_server.tools.finance import (
    calculate_interest,
    get_latest_lpr_rate,
    get_lpr_sync_status,
    list_lpr_rates,
    sync_lpr_rates,
)
from mcp_server.tools.image_rotation import (
    detect_orientation,
    detect_single_page_orientation,
    export_rotated_images,
    export_rotated_pdf,
    extract_pdf_pages,
    suggest_rename,
)
from mcp_server.tools.invoice_recognition import (
    download_invoices,
    get_invoice_task_status,
    quick_recognize_invoice,
    upload_invoices,
)
from mcp_server.tools.legal_research import (
    capability_search,
    check_law_references,
    create_research_task,
    download_all_research_results,
    download_research_result,
    get_research_task,
    list_research_results,
)
# 条件导入：信息中转站
_HAS_MESSAGE_HUB = False
try:
    from mcp_server.tools.message_hub import (
        create_message_source,
        delete_message_source,
        download_inbox_attachment,
        get_inbox_message,
        get_message_source,
        list_inbox_messages,
        list_message_sources,
        preview_inbox_attachment,
        rename_inbox_attachment,
        sync_all_message_sources,
        sync_message_source,
        update_message_source,
    )
    _HAS_MESSAGE_HUB = True
except ImportError:
    pass
from mcp_server.tools.oa_filing import (
    batch_create_cases,
    batch_create_clients,
    execute_case_import,
    get_case_import_preview,
    get_case_import_session,
    get_client_import_session,
    trigger_case_import,
    trigger_client_import,
)
from mcp_server.tools.organization import (
    create_credential,
    create_lawfirm,
    create_lawyer,
    create_team,
    delete_credential,
    delete_lawfirm,
    delete_lawyer,
    delete_team,
    get_credential,
    get_filing_status,
    get_lawfirm,
    get_lawyer,
    get_team,
    list_credentials,
    list_lawfirms,
    list_lawyers,
    list_oa_configs,
    list_teams,
    trigger_oa_filing,
    update_credential,
    update_lawfirm,
    update_lawyer,
    update_team,
)
from mcp_server.tools.pdf_splitting import (
    cancel_pdf_split,
    confirm_pdf_split,
    create_pdf_split_job,
    download_pdf_split_raw,
    download_pdf_split_result,
    get_pdf_split_job,
    get_pdf_split_page_preview,
)
from mcp_server.tools.reminders import (
    create_new_reminder,
    delete_reminder,
    get_finance_stats,
    get_reminder,
    get_target_options,
    list_all_reminders,
    list_payments,
    list_reminder_types,
    parse_reminders_from_text,
    update_reminder,
)
from mcp_server.tools.core import (
    chat_with_context,
    create_system_config,
    delete_schedule,
    delete_system_config,
    delete_task,
    generate_poi_complaint,
    generate_report,
    get_conversation_history,
    get_dashboard_stats,
    global_search,
    list_available_models,
    list_completed_tasks,
    list_failed_tasks,
    list_queued_tasks,
    list_scheduled_tasks,
    list_system_configs,
    patch_system_config,
    poi_health,
    resubmit_task,
    sync_prompt_templates,
    test_model_connection,
    update_system_configs,
)
from mcp_server.tools.web_search import web_search
from apps.workflow.mcp.workflow_tools import (
    approve_workflow_step,
    cancel_workflow,
    create_workflow_template,
    delete_workflow_run,
    delete_workflow_template,
    duplicate_workflow_template,
    get_step_registry,
    get_step_registry_flat,
    get_workflow_detail,
    get_workflow_template,
    list_workflow_templates,
    list_workflows,
    start_workflow,
    start_workflow_from_steps,
    update_workflow_template,
)

__all__ = [
    # 案件
    "list_cases",
    "search_cases",
    "get_case",
    "create_case",
    "update_case",
    "delete_case",
    "create_full_case",
    "list_case_parties",
    "add_case_party",
    "get_case_party",
    "update_case_party",
    "delete_case_party",
    "list_case_logs",
    "create_case_log",
    "get_case_log",
    "update_case_log",
    "delete_case_log",
    "list_case_numbers",
    "create_case_number",
    "get_case_number",
    "update_case_number",
    "delete_case_number",
    "list_case_assignments",
    "assign_lawyer",
    "get_case_assignment",
    "update_case_assignment",
    "delete_case_assignment",
    "list_grants",
    "create_grant",
    "get_grant",
    "update_grant",
    "delete_grant",
    "list_causes_data",
    "list_causes_tree",
    "get_cause",
    "list_courts_data",
    "calculate_litigation_fee",
    "list_bind_candidates",
    "bind_materials",
    "save_group_order",
    "rename_material_group",
    "delete_material",
    "delete_all_materials",
    "start_folder_scan",
    "list_scan_subfolders",
    "get_scan_status",
    "create_scan_stage",
    "create_case_folder_binding",
    "get_case_folder_binding",
    "delete_case_folder_binding",
    "get_contract_folder_path",
    "browse_case_folders",
    "list_case_cloud_storage_accounts",
    "list_template_bindings",
    "create_template_binding",
    "delete_template_binding",
    "list_available_templates",
    "generate_case_template",
    "unified_generate",
    # 客户
    "list_clients",
    "get_client",
    "create_client",
    "parse_client_text",
    "update_client",
    "delete_client",
    "list_clients_with_docs",
    "get_identity_doc_task",
    "submit_identity_doc_recognition",
    "merge_id_card_manual",
    "enterprise_search",
    "enterprise_prefill",
    "get_identity_doc",
    "delete_identity_doc",
    "list_property_clues",
    "create_property_clue",
    "get_property_clue",
    "update_property_clue",
    "delete_property_clue",
    "get_property_clue_content_template",
    "validate_id_card",
    "check_oa_credential",
    # 合同
    "list_contracts",
    "get_contract",
    "create_contract",
    "create_contract_with_cases",
    "update_contract",
    "delete_contract",
    "update_contract_lawyers",
    "get_contract_all_parties",
    # 合同收款
    "create_payment",
    "update_payment",
    "delete_payment",
    # 补充协议
    "list_supplementary_agreements",
    "get_supplementary_agreement",
    "create_supplementary_agreement",
    "update_supplementary_agreement",
    "delete_supplementary_agreement",
    # 合同文件夹
    "create_folder_binding",
    "get_folder_binding",
    "delete_folder_binding",
    "browse_folders",
    "list_cloud_storage_accounts",
    # 合同归档
    "learn_archive_rules",
    "get_archive_checklist",
    "download_archive_item",
    "generate_archive_folder",
    "toggle_compact_archive",
    "sync_case_materials",
    "reset_and_resync_case_materials",
    "scale_to_a4",
    "confirm_archive",
    "delete_archive_material",
    "reorder_archive_materials",
    "move_archive_material",
    "clear_all_archive_materials",
    # 合同文件夹扫描
    "start_contract_scan",
    "list_contract_scan_subfolders",
    "get_latest_contract_scan",
    "get_contract_scan_status",
    "confirm_contract_scan",
    # 提醒与财务
    "list_all_reminders",
    "get_reminder",
    "create_new_reminder",
    "update_reminder",
    "delete_reminder",
    "list_reminder_types",
    "parse_reminders_from_text",
    "get_target_options",
    "list_payments",
    "get_finance_stats",
    # 组织架构 - 律师
    "list_lawyers",
    "get_lawyer",
    "create_lawyer",
    "update_lawyer",
    "delete_lawyer",
    # 组织架构 - 律所
    "list_lawfirms",
    "get_lawfirm",
    "create_lawfirm",
    "update_lawfirm",
    "delete_lawfirm",
    # 组织架构 - 团队
    "list_teams",
    "get_team",
    "create_team",
    "update_team",
    "delete_team",
    # 组织架构 - 账号凭证
    "list_credentials",
    "get_credential",
    "create_credential",
    "update_credential",
    "delete_credential",
    # OA 立案
    "list_oa_configs",
    "trigger_oa_filing",
    "get_filing_status",
    # 企业数据
    "list_enterprise_providers",
    "search_companies",
    "get_company_profile",
    "get_company_risks",
    "get_company_shareholders",
    "get_company_personnel",
    "get_person_profile",
    "search_bidding_info",
    # 类案检索
    "create_research_task",
    "capability_search",
    "get_research_task",
    "list_research_results",
    "download_research_result",
    "download_all_research_results",
    "check_law_references",
    # 自动化
    "submit_court_sms",
    "list_court_sms",
    "get_court_sms_detail",
    "assign_sms_case",
    "retry_sms_processing",
    "delete_court_sms",
    "download_sms_documents",
    "download_sms_document",
    "get_captcha_image",
    "submit_captcha_answer",
    "auto_namer_process",
    "auto_namer_process_by_path",
    # 性能监控
    "health_check",
    "get_performance_metrics",
    "get_statistics_report",
    "get_resource_usage",
    "get_cache_statistics",
    "optimize_concurrency",
    "warm_up_cache",
    "clear_cache",
    "reset_performance_metrics",
    "cleanup_resources",
    # 文档处理器
    "process_document",
    "process_document_by_path",
    # 自动化主 API
    "ai_ollama",
    "get_automation_config",
    "get_automation_status",
    # PDF 拆解
    "create_pdf_split_job",
    "get_pdf_split_job",
    "confirm_pdf_split",
    "cancel_pdf_split",
    "download_pdf_split_result",
    "get_pdf_split_page_preview",
    "download_pdf_split_raw",
    # OA 导入
    "trigger_client_import",
    "get_client_import_session",
    "batch_create_clients",
    "trigger_case_import",
    "get_case_import_session",
    "get_case_import_preview",
    "execute_case_import",
    "batch_create_cases",
    # 要素式转换
    "list_doc_convert_types",
    "convert_document",
    # 文档转换
    "get_conversion_progress",
    "cancel_conversion_job",
    "download_converted_files",
    "delete_conversion_job",
    "doc_converter_health_check",
    "save_to_directory",
    # 联系人
    "list_contacts",
    "create_contact",
    "search_contacts",
    "get_contact",
    "update_contact",
    "delete_contact",
    # 发票识别
    "quick_recognize_invoice",
    "upload_invoices",
    "get_invoice_task_status",
    "download_invoices",
    # 聊天记录取证
    "create_project",
    "list_projects",
    "list_recordings",
    "list_screenshots",
    "create_export",
    "get_export_task",
    "get_export_types",
    "get_export_statuses",
    "download_export",
    "get_recording",
    "update_recording",
    "delete_recording",
    "extract_recording",
    "cancel_extract_recording",
    "reset_extract_recording",
    "update_screenshot",
    "delete_screenshot",
    "reorder_screenshots",
    # 合同审查
    "upload_contract_for_review",
    "get_review_status",
    "get_review_models",
    "confirm_party",
    "download_review_result",
    "download_review_original",
    "normalize_contract_format",
    "download_normalized_result",
    # 文书生产
    "list_document_templates",
    "get_document_template",
    "create_document_template",
    "list_folder_templates",
    "list_placeholders",
    "preview_placeholders",
    "preview_contract_context",
    "download_contract_document",
    "download_contract_folder",
    # 文书生产 - 模板操作
    "update_document_template",
    "delete_document_template",
    "extract_template_placeholders",
    "get_undefined_placeholders",
    "list_template_library_files",
    # 文件夹模板操作
    "get_folder_template",
    "create_folder_template",
    "update_folder_template",
    "delete_folder_template",
    "validate_folder_structure",
    # 替换词操作
    "get_placeholder",
    "get_placeholder_by_key",
    "create_placeholder",
    "update_placeholder",
    "delete_placeholder",
    # 文档生成操作
    "preview_supplementary_agreement_context",
    "preview_archive_context",
    "get_archive_overrides",
    "save_archive_overrides",
    "delete_archive_overrides",
    "download_supplementary_agreement",
    # 诉讼文书生成
    "generate_complaint",
    "generate_defense",
    "preview_litigation_context",
    "download_litigation_document",
    # 授权委托材料
    "download_authority_letter",
    "download_legal_rep_certificate",
    "download_power_of_attorney_combined",
    "download_authorization_package",
    "download_power_of_attorney",
    # 财产保全材料
    "download_preservation_application",
    "download_delay_delivery_application",
    "download_full_preservation_package",
    # 外部模板
    "analyze_template",
    "confirm_mappings",
    "preview_fill",
    "match_templates",
    "get_custom_fields",
    "get_fill_history",
    "get_statistics",
    "get_preview_html",
    "list_mappings",
    "create_mapping",
    "update_mapping",
    "delete_mapping",
    # 证据管理
    "reorder_evidence_items",
    # LPR 利率
    "list_lpr_rates",
    "get_latest_lpr_rate",
    "calculate_interest",
    "sync_lpr_rates",
    "get_lpr_sync_status",
    # 图片旋转
    "extract_pdf_pages",
    "detect_orientation",
    "suggest_rename",
    "detect_single_page_orientation",
    "export_rotated_pdf",
    "export_rotated_images",
    # 核心
    # LLM 服务
    "chat_with_context",
    "get_conversation_history",
    "sync_prompt_templates",
    "list_available_models",
    "test_model_connection",
    # 系统配置
    "list_system_configs",
    "update_system_configs",
    "create_system_config",
    "patch_system_config",
    "delete_system_config",
    # 仪表盘
    "get_dashboard_stats",
    # 全局搜索
    "global_search",
    # 任务队列
    "list_queued_tasks",
    "list_completed_tasks",
    "list_failed_tasks",
    "list_scheduled_tasks",
    "delete_task",
    "delete_schedule",
    "resubmit_task",
    # POI 文档生成
    "poi_health",
    "generate_poi_complaint",
    "generate_report",
    # 网络搜索
    "web_search",
    # 工作流引擎
    "start_workflow",
    "list_workflows",
    "get_workflow_detail",
    "approve_workflow_step",
    "cancel_workflow",
    "delete_workflow_run",
    # 工作流模板管理
    "get_step_registry",
    "get_step_registry_flat",
    "create_workflow_template",
    "update_workflow_template",
    "list_workflow_templates",
    "get_workflow_template",
    "delete_workflow_template",
    "duplicate_workflow_template",
    "start_workflow_from_steps",
]

# 条件导出：网上立案
if _HAS_FILING:
    __all__ += [
        "get_court_filing_case_info",
        "get_court_filing_session",
        "execute_court_filing",
    ]

# 条件导出：诉讼保全
if _HAS_GUARANTEE:
    __all__ += [
        "get_guarantee_case_info",
        "get_guarantee_session",
        "execute_guarantee",
        "ensure_guarantee_quote",
        "bind_guarantee_quote",
        "delete_guarantee_quote",
        "retry_guarantee_quote",
        "delete_guarantee_binding",
    ]

# 条件导出：财产保全询价
if _HAS_QUOTE:
    __all__ += [
        "create_preservation_quote",
        "list_preservation_quotes",
        "get_preservation_quote",
        "execute_preservation_quote",
        "retry_preservation_quote",
    ]

# 条件导出：信息中转站
if _HAS_MESSAGE_HUB:
    __all__ += [
        "list_inbox_messages",
        "get_inbox_message",
        "rename_inbox_attachment",
        "download_inbox_attachment",
        "preview_inbox_attachment",
        "list_message_sources",
        "get_message_source",
        "create_message_source",
        "update_message_source",
        "delete_message_source",
        "sync_message_source",
        "sync_all_message_sources",
    ]
