# Generated by Django 6.0.6 on 2026-06-14 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_converter', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='docconverteritem',
            index=models.Index(fields=['job', 'created_at'], name='doc_conv_item_job_idx'),
        ),
    ]
