# Generated by Django 6.0.6 on 2026-06-16 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("doc_converter", "0002_add_performance_indexes_round2"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="docconverteritem",
            name="doc_conv_item_job_idx",
        ),
    ]
