# Generated by Django 6.0.6 on 2026-06-14 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_rotation', '0003_add_onnx_rotation'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='imagerotationpage',
            index=models.Index(fields=['job', 'page_number'], name='image_rot_page_job_idx'),
        ),
    ]
