# Generated by Django 6.0.6 on 2026-06-16 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("image_rotation", "0004_add_performance_indexes_round2"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="imagerotationpage",
            name="image_rot_page_job_idx",
        ),
    ]
