# Generated by Django 6.0.4 on 2026-05-07 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workbench', '0003_add_summary_file_to_batch_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchjob',
            name='started_processing_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='首个文件开始处理时间'),
        ),
    ]
