# Generated by Django 6.0.5 on 2026-06-04 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_add_cloud_storage_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="cloudstorageaccount",
            name="dropbox_access_token",
            field=models.TextField(blank=True, default="", verbose_name="Access Token（加密）"),
        ),
        migrations.AddField(
            model_name="cloudstorageaccount",
            name="dropbox_app_key",
            field=models.CharField(blank=True, default="", max_length=255, verbose_name="App Key"),
        ),
        migrations.AddField(
            model_name="cloudstorageaccount",
            name="dropbox_app_secret",
            field=models.CharField(blank=True, default="", max_length=512, verbose_name="App Secret（加密存储）"),
        ),
        migrations.AddField(
            model_name="cloudstorageaccount",
            name="dropbox_refresh_token",
            field=models.TextField(blank=True, default="", verbose_name="Refresh Token（加密）"),
        ),
        migrations.AddField(
            model_name="cloudstorageaccount",
            name="dropbox_root_path",
            field=models.CharField(blank=True, default="/", max_length=1000, verbose_name="Dropbox 根路径"),
        ),
        migrations.AddField(
            model_name="cloudstorageaccount",
            name="dropbox_token_expires_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Dropbox Token 过期时间"),
        ),
        migrations.AddField(
            model_name="cloudstorageaccount",
            name="gdrive_root_folder_id",
            field=models.CharField(blank=True, default="root", max_length=255, verbose_name="根文件夹 ID"),
        ),
        migrations.AddField(
            model_name="cloudstorageaccount",
            name="gdrive_root_path",
            field=models.CharField(blank=True, default="/", max_length=1000, verbose_name="Google Drive 根路径"),
        ),
        migrations.AddField(
            model_name="cloudstorageaccount",
            name="gdrive_service_account_json",
            field=models.TextField(blank=True, default="", verbose_name="Service Account JSON（加密存储）"),
        ),
        migrations.AddField(
            model_name="cloudstorageaccount",
            name="s3_access_key_id",
            field=models.CharField(blank=True, default="", max_length=255, verbose_name="Access Key ID"),
        ),
        migrations.AddField(
            model_name="cloudstorageaccount",
            name="s3_bucket_name",
            field=models.CharField(blank=True, default="", max_length=255, verbose_name="Bucket 名称"),
        ),
        migrations.AddField(
            model_name="cloudstorageaccount",
            name="s3_endpoint_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="留空使用 AWS 默认；S3 兼容服务填对应地址",
                verbose_name="Endpoint URL",
            ),
        ),
        migrations.AddField(
            model_name="cloudstorageaccount",
            name="s3_region",
            field=models.CharField(blank=True, default="us-east-1", max_length=50, verbose_name="Region"),
        ),
        migrations.AddField(
            model_name="cloudstorageaccount",
            name="s3_root_path",
            field=models.CharField(blank=True, default="/", max_length=1000, verbose_name="S3 根路径"),
        ),
        migrations.AddField(
            model_name="cloudstorageaccount",
            name="s3_secret_access_key",
            field=models.CharField(
                blank=True, default="", max_length=512, verbose_name="Secret Access Key（加密存储）"
            ),
        ),
        migrations.AlterField(
            model_name="cloudstorageaccount",
            name="name",
            field=models.CharField(help_text="如：坚果云、123云盘", max_length=100, verbose_name="存储名称"),
        ),
        migrations.AlterField(
            model_name="cloudstorageaccount",
            name="storage_type",
            field=models.CharField(
                choices=[
                    ("local", "本地文件系统"),
                    ("webdav", "WebDAV"),
                    ("onedrive", "OneDrive"),
                    ("s3", "S3 兼容存储"),
                    ("google_drive", "Google Drive"),
                    ("dropbox", "Dropbox"),
                ],
                default="local",
                max_length=20,
                verbose_name="存储类型",
            ),
        ),
    ]
