# Generated by Django 6.0.6 on 2026-06-22 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_systemconfig_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedisQueueTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Valkey 任务队列',
                'verbose_name_plural': 'Valkey 任务队列',
                'managed': False,
            },
        ),
    ]
