"""项目共享常量"""

# ── 文件大小限制 ──
DEFAULT_MAX_FILE_SIZE = 20 * 1024 * 1024  # 20MB
LARGE_FILE_MAX_SIZE = 50 * 1024 * 1024  # 50MB
VIDEO_MAX_SIZE = 2 * 1024 * 1024 * 1024  # 2GB

# ── 日期格式 ──
DATE_FORMAT_COMPACT = "%Y%m%d"
DATE_FORMAT_STANDARD = "%Y-%m-%d"
DATETIME_FORMAT_FULL = "%Y-%m-%d %H:%M:%S"
DATETIME_FORMAT_FILESAFE = "%Y%m%d_%H%M%S"
DATE_FORMAT_CHINESE = "%Y年%m月%d日"

# ── HTTP 超时 ──
DEFAULT_REQUEST_TIMEOUT = 30  # 秒
LONG_REQUEST_TIMEOUT = 120  # 秒
