# Generated by Django 6.0.6 on 2026-06-14 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_hub', '0007_add_messagesource_source_type_idx'),
        ('organization', '0007_alter_lawyer_license_pdf'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='messagesource',
            index=models.Index(fields=['is_enabled'], name='message_hub_is_enab_c8fd8c_idx'),
        ),
    ]
