# Generated by Django 6.0.6 on 2026-06-16 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("message_hub", "0008_add_performance_indexes"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="messagesource",
            name="message_hub_is_enab_c8fd8c_idx",
        ),
    ]
