# Generated by Django 6.0.5 on 2026-05-23 13:51

import apps.core.filesystem.upload_paths
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0007_alter_lawyer_license_pdf'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('search', '检索模式'), ('direct', '直投模式')], default='search', max_length=16, verbose_name='模式')),
                ('keyword', models.CharField(blank=True, max_length=255, verbose_name='检索关键词')),
                ('case_summary', models.TextField(blank=True, verbose_name='案情简述')),
                ('direct_content', models.TextField(blank=True, verbose_name='直投内容')),
                ('source_doc_id', models.CharField(blank=True, max_length=255, verbose_name='威科文档ID')),
                ('source_title', models.CharField(blank=True, max_length=512, verbose_name='文书标题')),
                ('source_court_text', models.CharField(blank=True, max_length=255, verbose_name='法院')),
                ('source_judgment_date', models.CharField(blank=True, max_length=64, verbose_name='裁判日期')),
                ('source_facts', models.TextField(blank=True, verbose_name='案件事实')),
                ('voice', models.CharField(default='冰糖', max_length=32, verbose_name='TTS音色')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('queued', '队列中'), ('running', '执行中'), ('completed', '已完成'), ('failed', '失败'), ('cancelled', '已取消')], default='pending', max_length=16, verbose_name='状态')),
                ('progress', models.PositiveIntegerField(default=0, verbose_name='进度')),
                ('message', models.CharField(blank=True, max_length=255, verbose_name='状态描述')),
                ('error', models.TextField(blank=True, verbose_name='错误信息')),
                ('q_task_id', models.CharField(blank=True, max_length=64, verbose_name='队列任务ID')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_ops_tasks', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('credential', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='content_ops_tasks', to='organization.accountcredential', verbose_name='威科先行凭证')),
            ],
            options={
                'verbose_name': '内容运营任务',
                'verbose_name_plural': '内容运营任务',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='文章标题')),
                ('content', models.TextField(verbose_name='正文')),
                ('source_summary', models.TextField(blank=True, verbose_name='原始内容摘要')),
                ('review_status', models.CharField(choices=[('draft', '待审核'), ('approved', '已通过'), ('rejected', '已驳回')], default='draft', max_length=16, verbose_name='审核状态')),
                ('reviewer_notes', models.TextField(blank=True, verbose_name='审核备注')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('llm_model', models.CharField(blank=True, max_length=128, verbose_name='使用的模型')),
                ('token_usage', models.JSONField(blank=True, default=dict, verbose_name='Token用量')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='content_ops.contenttask', verbose_name='任务')),
            ],
            options={
                'verbose_name': '生成文章',
                'verbose_name_plural': '生成文章',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PodcastEpisode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voice', models.CharField(max_length=32, verbose_name='TTS音色')),
                ('audio_file', models.FileField(blank=True, max_length=255, upload_to=apps.core.filesystem.upload_paths.DatedUUIDPath('content_ops/audio'), verbose_name='音频文件')),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True, verbose_name='时长(秒)')),
                ('file_size_bytes', models.PositiveIntegerField(blank=True, null=True, verbose_name='文件大小(字节)')),
                ('review_status', models.CharField(choices=[('draft', '待审核'), ('approved', '已通过'), ('rejected', '已驳回')], default='draft', max_length=16, verbose_name='审核状态')),
                ('reviewer_notes', models.TextField(blank=True, verbose_name='审核备注')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='content_ops.generatedarticle', verbose_name='文章')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='content_ops.contenttask', verbose_name='任务')),
            ],
            options={
                'verbose_name': '播客单集',
                'verbose_name_plural': '播客单集',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='contenttask',
            index=models.Index(fields=['status', '-created_at'], name='content_ops_status_708720_idx'),
        ),
        migrations.AddIndex(
            model_name='contenttask',
            index=models.Index(fields=['created_by', '-created_at'], name='content_ops_created_7e13e9_idx'),
        ),
        migrations.AddIndex(
            model_name='contenttask',
            index=models.Index(fields=['mode', '-created_at'], name='content_ops_mode_c779b4_idx'),
        ),
    ]
