# Generated by Django 6.0.5 on 2026-05-23 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_ops', '0001_initial'),
        ('organization', '0007_alter_lawyer_license_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenttask',
            name='credential',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='content_ops_tasks', to='organization.accountcredential', verbose_name='法律检索网站账号'),
        ),
    ]
