# Generated by Django 6.0.5 on 2026-05-23 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_ops', '0002_alter_contenttask_credential'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenttask',
            name='tts_style_prompt',
            field=models.TextField(blank=True, default='', help_text='自然语言描述期望的声音风格，使用 VoiceDesign 模式合成。留空则使用内置音色。', verbose_name='VoiceDesign 音色描述'),
        ),
    ]
