# Generated by Django 6.0.6 on 2026-06-20 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docspace', '0002_seed_default_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='docspacedocument',
            name='web_url',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='DocSpace 编辑器 URL'),
        ),
    ]
