# Generated by Django 6.0.6 on 2026-06-14 12:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0025_alter_casefolderbinding_storage_type'),
        ('workflow', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='workflowrun',
            index=models.Index(fields=['case', 'status'], name='workflow_wo_case_id_61f540_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowrun',
            index=models.Index(fields=['template'], name='workflow_wo_templat_cbac02_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowrun',
            index=models.Index(fields=['status', '-started_at'], name='workflow_wo_status_290180_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowtemplate',
            index=models.Index(fields=['category', 'is_active'], name='workflow_wo_categor_1020b5_idx'),
        ),
    ]
