# Generated by Django 6.0.6 on 2026-06-16 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0002_add_performance_indexes"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="workflowrun",
            name="workflow_wo_case_id_61f540_idx",
        ),
        migrations.RemoveIndex(
            model_name="workflowrun",
            name="workflow_wo_templat_cbac02_idx",
        ),
        migrations.RemoveIndex(
            model_name="workflowrun",
            name="workflow_wo_status_290180_idx",
        ),
        migrations.RemoveIndex(
            model_name="workflowtemplate",
            name="workflow_wo_categor_1020b5_idx",
        ),
    ]
