# Generated by Django 6.0.6 on 2026-06-12 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0014_alter_gsxtreporttask_report_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapertask',
            name='captcha_answer',
            field=models.CharField(blank=True, help_text='用户手动输入的验证码答案', max_length=64, null=True, verbose_name='验证码答案'),
        ),
        migrations.AddField(
            model_name='scrapertask',
            name='captcha_image_path',
            field=models.CharField(blank=True, help_text='手动验证码模式下存储待识别图片路径', max_length=500, null=True, verbose_name='验证码图片路径'),
        ),
        migrations.AlterField(
            model_name='scrapertask',
            name='status',
            field=models.CharField(choices=[('pending', '等待中'), ('running', '执行中'), ('waiting_for_captcha', '等待验证码'), ('success', '成功'), ('failed', '失败')], default='pending', max_length=32, verbose_name='状态'),
        ),
    ]
