# Generated by Django 6.0.6 on 2026-06-14 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0015_add_captcha_manual_fields'),
        ('cases', '0025_alter_casefolderbinding_storage_type'),
        ('client', '0009_add_performance_indexes'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='courtsms',
            index=models.Index(fields=['status', 'created_at'], name='automation__status_40c207_idx'),
        ),
        migrations.AddIndex(
            model_name='gsxtreporttask',
            index=models.Index(fields=['client'], name='automation__client__291c1f_idx'),
        ),
        migrations.AddIndex(
            model_name='gsxtreporttask',
            index=models.Index(fields=['status', '-created_at'], name='automation__status_5f0083_idx'),
        ),
    ]
