# Generated by Django 6.0.6 on 2026-06-16 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0016_add_performance_indexes"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="courtsms",
            name="automation__status_40c207_idx",
        ),
        migrations.RemoveIndex(
            model_name="gsxtreporttask",
            name="automation__client__291c1f_idx",
        ),
        migrations.RemoveIndex(
            model_name="gsxtreporttask",
            name="automation__status_5f0083_idx",
        ),
    ]
