# Generated by Django 6.0.6 on 2026-06-19 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0017_remove_courtsms_automation__status_40c207_idx_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageRotation',
        ),
    ]
