# Generated by Django 6.0.6 on 2026-06-22 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0018_delete_imagerotation'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='documentdeliveryschedule',
            name='automation__is_acti_ebd2c4_idx',
        ),
        migrations.RemoveIndex(
            model_name='documentdeliveryschedule',
            name='automation__credent_eb5b93_idx',
        ),
        migrations.AlterUniqueTogether(
            name='documentqueryhistory',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='documentqueryhistory',
            name='automation__credent_76d5df_idx',
        ),
        migrations.RemoveIndex(
            model_name='documentqueryhistory',
            name='automation__send_ti_17ce8b_idx',
        ),
        migrations.RemoveField(
            model_name='documentqueryhistory',
            name='court_sms',
        ),
        migrations.RemoveField(
            model_name='documentqueryhistory',
            name='credential',
        ),
        migrations.DeleteModel(
            name='DocumentDeliverySchedule',
        ),
        migrations.DeleteModel(
            name='DocumentQueryHistory',
        ),
    ]
