# Generated by Django 6.0.6 on 2026-06-21 10:09

import apps.core.model_fields.encrypted
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_alter_lawyer_license_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountcredential',
            name='password',
            field=apps.core.model_fields.encrypted.EncryptedTextField(verbose_name='密码'),
        ),
    ]
