# Generated by Django 6.0.6 on 2026-06-14 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0011_remove_smart_fill_proxy'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='evidenceitem',
            index=models.Index(fields=['direction'], name='documents_e_directi_22020a_idx'),
        ),
        migrations.AddIndex(
            model_name='evidenceitem',
            index=models.Index(fields=['evidence_type'], name='documents_e_evidenc_e2bfc0_idx'),
        ),
        migrations.AddIndex(
            model_name='evidenceitem',
            index=models.Index(fields=['original_status'], name='documents_e_origina_c934bd_idx'),
        ),
    ]
