# Generated by Django 6.0.6 on 2026-06-16 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0012_add_performance_indexes"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="evidenceitem",
            name="documents_e_directi_22020a_idx",
        ),
        migrations.RemoveIndex(
            model_name="evidenceitem",
            name="documents_e_evidenc_e2bfc0_idx",
        ),
        migrations.RemoveIndex(
            model_name="evidenceitem",
            name="documents_e_origina_c934bd_idx",
        ),
    ]
