# Generated by Django 6.0.5 on 2026-06-04 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract_review', '0011_reviewtask_pdf_cache_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormatNormalize',
            fields=[
            ],
            options={
                'verbose_name': '格式调整',
                'verbose_name_plural': '格式调整',
                'ordering': ['-created_at'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('contract_review.reviewtask',),
        ),
    ]
