# Generated by Django 6.0.5 on 2026-05-12 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0030_alter_finalizedmaterial_archive_item_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractfolderbinding',
            name='folder_device',
            field=models.BigIntegerField(blank=True, help_text='文件夹所在设备号，与 inode 配合使用', null=True, verbose_name='设备号'),
        ),
    ]
