# Generated by Django 6.0.5 on 2026-06-04 07:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_add_performance_indexes'),
        ('contracts', '0030_add_cloud_storage_to_folder_bindings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='contractassignment',
            index=models.Index(fields=['lawyer'], name='contracts_c_lawyer__3c302f_idx'),
        ),
        migrations.AddIndex(
            model_name='supplementaryagreementparty',
            index=models.Index(fields=['client'], name='contracts_s_client__e51df2_idx'),
        ),
    ]
