# Generated by Django 6.0.6 on 2026-06-19 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0034_add_timestamps_to_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalcontract',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='historicalcontract',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='更新时间'),
        ),
    ]
